version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8501}:${PORT:-8501}"
    volumes:
      - .:/app
    environment:
      - PORT=${PORT:-8501}
      - STREAMLIT_SERVER_PORT=${PORT:-8501}
      - PYTHONUNBUFFERED=1
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    command: streamlit run app.py --server.port=${PORT:-8501} --server.address=0.0.0.0